#!/bin/bash
export GDK_SCALE=2
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1.2
export MOZ_USE_XINPUT2=1

xautolock -time 15 -locker i3lock &

xrdb .Xresources

xrandr --output eDP-1 --primary --mode 3840x2400 --pos 4480x0 --output DP-1 --mode 2560x1440 --pos 0x0 --scale 1.75x1.75

exec i3
-
